description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10.22.0
    - uses: actions/setup-node@v6
      with:
        node-version: '24.11.1'
        cache: pnpm
    - run: pnpm install
      shell: bash
  using: composite